routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::resource('/user','UserController');

Route::post('/cart/check-out-with-paypal','CartController@pay');

Route::get('/order/processed','CartController@success');
Route::get('/paypal/payment','CartController@paymentStatus');
Route::post('/cart/delete-item','CartController@delete_item');
Route::resource('/cart','CartController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_type','username','name', 'email','website','api_client_id','api_secret_key','access_key', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/UserType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    //
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->authors = User::where('user_type',2)->get();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('layouts.pages.user.index')
                ->with('authors',$this->authors);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts.pages.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
           
        if($request->cpassword == $request->password ){
             
                $user = User::create([
                    'user_type' => 2,
                    'username'  => $request->username,
                    'name'      => $request->name,
                    'email'     => $request->email,
                    'website'   => $request->website,
                    'api_client_id'=> $request->api_client_id,
                    'api_secret_key'=>$request->api_secret_key,
                    'access_key'=>bcrypt($request->email),
                    'password'  =>bcrypt($request->password) 
                ]);

         }else{

            session()->flash('error_message','Password and Confirm Password did not match!');  

            return redirect()->back();
         }      

             session()->flash('message','Author successfully added!');  

            return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/pages/user/create.blade.php
@extends('layouts.template.master')

@section('custom_css')

@endsection

@section('content')
     <!-- Start Content-->
     <div class="container-fluid">
                        
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Folioavenue</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Forms</a></li>
                                <li class="breadcrumb-item active">Add New User Author</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Add New User Author</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('user.store') }}" method="POST" role="form">
                                    @csrf
                          
                                <div class="row">
                                    <div class="col-lg-6">
                                            <h4 class="header-title">Author Information</h4>

                                            <div class="form-group mb-3">
                                                <label for="name">Name</label>
                                                <input type="text" id="name" class="form-control" name="name" placeholder="name" required>
                                            </div>

                                            <div class="form-group mb-3">
                                                <label for="email">Email</label>
                                                <input type="email" id="email" class="form-control" name="email" placeholder="Email" required>
                                            </div>
                                            
                                            <div class="form-group mb-3">
                                                <label for="website">Website</label>
                                                <input type="text" id="website" class="form-control" name="website" placeholder="http://" required>
                                            </div>

                                            <div class="form-group mb-3">
                                                <label for="api_client_id">Api CLient ID</label>
                                                <input type="password" id="api_client_id" class="form-control" name="api_client_id" placeholder="Api CLient ID" required>
                                            </div>

                                            <div class="form-group mb-3">
                                                <label for="api_secret_key">Api Secret Key</label>
                                                <input type="password" id="api_secret_key" name="api_secret_key" class="form-control" placeholder="Api Secret Key" required>
                                            </div>  
                                    
                                    </div> <!-- end col -->
                                    <div class="col-lg-6">
                                            <h4 class="header-title">Credentials</h4>
                                            <div class="form-group mb-3">
                                                <label for="username">Username</label>
                                                <input type="text" id="username" class="form-control" name="username" placeholder="Username" required>
                                            </div>

                                            <div class="form-group mb-3">
                                                    <label for="password">Password</label>
                                                    <input type="password" id="password" class="form-control" name="password" placeholder="Password" required>
                                                </div>
                                                <div class="form-group mb-3">
                                                        <label for="cpassword">Confirm Password</label>
                                                        <input type="password" id="cpassword" class="form-control" name="cpassword" placeholder="Confirm Password" required>
                                                </div>
                                    </div>     
                                     <button type="submit" class="btn btn-success btn-block">Save</button>                                                    
                                </div>
                                <!-- end row-->
                             </form>
                        </div> <!-- end card-body -->
                    </div> <!-- end card -->
                </div><!-- end col -->
            </div>
            <!-- end row -->       
            
        </div> <!-- container -->
@endsection

@section('custom_js')
    
   

@endsection

resources/views/layouts/pages/user/index.blade.php
@extends('layouts.template.master')

@section('custom_css')
    <link href="{{ asset('vendor/hyper/assets/css/vendor/dataTables.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
    
    <link href="{{ asset('vendor/hyper/assets/css/vendor/responsive.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
     <!-- Start Content-->
     <div class="container-fluid">
                        
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Folioavenue</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Author Lists</a></li>
                           
                            </ol>
                        </div>
                        <h4 class="page-title">Author Lists</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <a class="btn btn-success btn-block" href="{{ url('/user/create') }}">Add New Author</a>
                            <br>       
                            <table id="authorstable" class="table dt-responsive nowrap">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Email</th>
                                                <th>Website</th>
                                                <th>Access key</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($authors as $author)
                                                <tr>
                                                    <td>{{ ucfirst($author->name) }}</td>
                                                    <td>{{ $author->email }}</td>
                                                    <td><a href="{{ $author->website }}" target="_blank">{{ $author->website}}</a></td>
                                                    <td>{{ $author->access_key }}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    
                                    </table>                       
                        </div> <!-- end card-body -->
                    </div> <!-- end card -->
                </div><!-- end col -->
            </div>
            <!-- end row -->                   
        </div> <!-- container -->
@endsection

@section('custom_js')    
    <script src="{{ asset('vendor/hyper/assets/js/vendor/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('vendor/hyper/assets/js/vendor/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('vendor/hyper/assets/js/vendor/dataTables.responsive.min.js') }}"></script>

    <script>
        $(document).ready(function(){                         
                $("#authorstable").DataTable();
        });
    </script>

@endsection

resources/views/layouts/pages/user/success_order.blade.php
@extends('layouts.template.master_cart')

@section('content')
<div class="content-page">
        <div class="content">
            
            <!-- Start Content-->
            <div class="container-fluid">

                <!-- start page title -->
               
                <!-- end page title -->
            <form action="{{ url('/cart/check-out-with-paypal') }}" role="form" method="POST">
                    @csrf
                <div class="row" style="margin-top:10%;">
                        <div class="col-xl-12">
                            <div class="card">
                                <div class="card-body">
                                    <div id="empty-cart" style="text-align:center;">
                                        <span><i class=" mdi mdi-approval text-success" style="font-size:100px;"></i></span>
                                        <h1 class="text-success">Your order has been succesfully processed!</h1>
                                    <a href="#" class="btn btn-success"><i class="mdi mdi-arrow-left"></i> go back to book store</a>
                                    </div>
                                    <br>
                                    <br>
                                    
                                </div> <!-- end card body-->
                                
                            </div> <!-- end card -->
                          
                        </div><!-- end col-->

                                     
                    </div>
                </form>
                    <!-- end row-->
                
            </div> <!-- container -->

        </div> <!-- content -->

        <!-- Footer Start -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div style="text-align:center">
                            2018 © <a href="folioavenue.com" style="color:#0acf97">Folioavenue</a> 
                        </div>
                    </div>
                    
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->

    </div>
@endsection